stages:
  - build_ci
build:
  stage: build_ci
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -f dockers/rust_ci/Dockerfile -t chandlersong/rust_ci:{image_tag}
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push chandlersong/rust_ci:{image_tag}
  when: manual  # 手动触发
  variables:
    image_tag: "1.85-slim-bookworm.1"  # 默认值
