stages:
  - build_ci
variables:
  image_tag: "1.85-slim-bookworm.1"  # 默认值
build_and_push:
  stage: build_ci
  image: docker:20.10  # 使用带有 Docker CLI 的镜像
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375  # 指定 Docker 守护进程地址
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -f dockers/rust_ci/Dockerfile -t chandlersong/rust_ci:{image_tag}
    - docker push chandlersong/rust_ci:{image_tag}
  when: manual  # 手动触发
