[workspace]
resolver = "2"



members = [
    "TraitTest",
    "ut_example", "cache_example",
    "concurrency_test"
, "websocket_ex", "rocksdbTest"]


[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
futures-util ="0.3.30"
