[workspace]
resolver = "2"



members = [
    "TraitTest",
    "UnitTestExample",
    "concurrency_test"
, "websocket_ex"]


[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
futures-util ="0.3.30"
