[package]
name = "reqwest_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["json"] }
tokio = {workspace = true}
serde = "1.0.219"
wiremock = "0.6"  # 示例：使用 wiremock 作为 mock server
