[package]
name = "UnitTestExample"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall_double = "0.3.1"
tokio = { version = "1", features = ["full"] }
double = "0.2.4"
async-trait = "0.1.85"

[dev-dependencies]
mockall = "0.12.0"
