[package]
name = "cache_example"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.54.0"
moka = { version = "0.12.10", features = ["future"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3.30"


[dependencies.web-time]
version = "^1.1.0"
