name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: '1.89-slim-bookworm'

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push rust_ci image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rust_ci/Dockerfile
          push: true
          tags: chandlersong/rust_ci:${{ inputs.image_tag }}

      - name: Build and push rust_runtime image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rust_runtime/Dockerfile
          push: true
          tags: chandlersong/rust_runtime:${{ inputs.image_tag }}
