name: Build and Push Docker Images (Multi-Arch)
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: '1.89-slim-bookworm'
jobs:
  build_amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push rocksdb image (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rocksdb/Dockerfile
          push: true
          platforms: linux/amd64
          tags: chandlersong/rocksdb:bookworm-slim-9.9.3

      - name: Build and push rust_ci image (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rust_ci/Dockerfile
          push: true
          platforms: linux/amd64
          tags: chandlersong/rust_ci:${{ inputs.image_tag }}-amd64

      - name: Build and push rust_runtime image (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rust_runtime/Dockerfile
          push: true
          platforms: linux/amd64
          tags: chandlersong/rust_runtime:${{ inputs.image_tag }}-amd64

  build_arm64:
    runs-on: ubuntu-24.04-arm
    needs: build_amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push rocksdb image (arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rocksdb/Dockerfile
          push: true
          platforms: linux/arm64
          tags: chandlersong/rocksdb:bookworm-slim-9.9.3

      - name: Build and push rust_ci image (arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rust_ci/Dockerfile
          push: true
          platforms: linux/arm64
          tags: chandlersong/rust_ci:${{ inputs.image_tag }}-arm64

      - name: Build and push rust_runtime image (arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rust_runtime/Dockerfile
          push: true
          platforms: linux/arm64
          tags: chandlersong/rust_runtime:${{ inputs.image_tag }}-arm64

  build_manifest:
    runs-on: ubuntu-latest
    needs: [build_amd64, build_arm64]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push multi-arch manifest for rust_ci
        run: |
          docker manifest create chandlersong/rust_ci:${{ inputs.image_tag }} \
            chandlersong/rust_ci:${{ inputs.image_tag }}-amd64 \
            chandlersong/rust_ci:${{ inputs.image_tag }}-arm64
          docker manifest push chandlersong/rust_ci:${{ inputs.image_tag }}

      - name: Create and push multi-arch manifest for rust_runtime
        run: |
          docker manifest create chandlersong/rust_runtime:${{ inputs.image_tag }} \
            chandlersong/rust_runtime:${{ inputs.image_tag }}-amd64 \
            chandlersong/rust_runtime:${{ inputs.image_tag }}-arm64
          docker manifest push chandlersong/rust_runtime:${{ inputs.image_tag }}
