name: Build and Push Docker Images (Multi-Arch)
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: '1.89-slim-bookworm'
jobs:
  build_x86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push rocksdb image (native x86_64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rocksdb/Dockerfile
          push: true
          platforms: linux/amd64
          tags: chandlersong/rocksdb:bookworm-slim-9.9.3

      - name: Build and push rust_ci image (native x86_64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rust_ci/Dockerfile
          push: true
          platforms: linux/amd64
          tags: chandlersong/rust_ci:${{ inputs.image_tag }}

      - name: Build and push rust_runtime image (native x86_64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rust_runtime/Dockerfile
          push: true
          platforms: linux/amd64
          tags: chandlersong/rust_runtime:${{ inputs.image_tag }}

  build_arm64:
    # 在 GitHub 提供的 arm64 runner 上原生构建（无需 QEMU）
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push rocksdb image (native arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rocksdb/Dockerfile
          push: true
          platforms: linux/arm64
          tags: chandlersong/rocksdb:bookworm-slim-9.9.3

      - name: Build and push rust_ci image (native arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rust_ci/Dockerfile
          push: true
          platforms: linux/arm64
          tags: chandlersong/rust_ci:${{ inputs.image_tag }}

      - name: Build and push rust_runtime image (native arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/rust_runtime/Dockerfile
          push: true
          platforms: linux/arm64
          tags: chandlersong/rust_runtime:${{ inputs.image_tag }}
